<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ITMartinFileSorter.Server</RootNamespace>
    <UserSecretsId>458c4573-c8af-4090-9315-d1d262cc09d5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ITMartin.Media.Application\ITMartin.Media.Application.csproj" />
    <ProjectReference Include="..\ITMartin.Media.Domain\ITMartin.Media.Domain.csproj" />
    <ProjectReference Include="..\ITMartin.Media.Infrastructure\ITMartin.Media.Infrastructure.csproj" />
    <ProjectReference Include="..\ITMartin.OCR\ITMartin.OCR.csproj" />
    <ProjectReference Include="..\ITMartin.Shared.UI\ITMartin.Shared.UI.csproj" />
    <ProjectReference Include="..\ITMartinFileSorter.Application\ITMartinFileSorter.Application.csproj" />
    <ProjectReference Include="..\ITMartinFileSorter.Domain\ITMartinFileSorter.Domain.csproj" />
    <ProjectReference Include="..\ITMartinFileSorter.Infrastructure\ITMartinFileSorter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="WebPush" Version="1.0.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ffmpeg\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Remove="appsettings.Development.json.disabled" />
  </ItemGroup>
  
  <!-- Media temp folder for thumbnails -->
  <ItemGroup>
    <Folder Include="wwwroot\media_temp\" />
    <Folder Include="wwwroot\media_temp\thumbnails\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="ffmpeg\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  

  <ItemGroup>
    <Content Remove="wwwroot\media_temp\thumbnails\F5D76417A6F27F15EC3682BC00AD26A8FCA37BF5ADE9B3220A49D755021DA718.jpg" />
  </ItemGroup>
  
</Project>