version: "3.8"

services:
  image-processor:
    build:
      context: /volume1/docker/image-processor

    container_name: image-processor
    restart: always

    volumes:
      # 🔥 SHARED SPACE (THIS is the key fix)
      - /volume1/photo:/data/input

      # output
      - /volume1/docker/image-processor/out:/data/ready

      # archive
      - /volume1/docker/image-processor/archive:/data/archive

    working_dir: /app
    command: dotnet ITMartinImageProcessor.Worker.dll