services:

  filesorter-web:
    container_name: filesorter-web
    build: ./filesorter
    ports:
      - "8080:8080"
    volumes:
      - /volume1/photo:/data
      - /volume1/docker/filesorter/library:/library
    restart: unless-stopped

  budget-web:
    container_name: budget-web
    build: ./budget
    ports:
      - "8081:8080"
    restart: unless-stopped

  image-processor:
    container_name: image-processor
    build: ./imageprocessor
    volumes:
      - /volume1/docker/imageprocessor/input:/data
      - /volume1/docker/imageprocessor/output:/library
      - /volume1/docker/imageprocessor/archive:/archive
    restart: unless-stopped