services:

  filesorter-web:
    container_name: filesorter-web
    build: ./filesorter

    ports:
      - "8080:8080"

    environment:
      - ASPNETCORE_URLS=http://+:8080

    volumes:
      - /volume1/docker/filesorter/incoming:/data
      - /volume1/docker/filesorter/library:/library
      - /volume1/docker/filesorter/config:/config

    restart: unless-stopped

    networks:
      - martinnet

  budget-web:
    container_name: budget-web
    build: ./budget
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - /volume1/docker/budget/data:/app/data
    restart: unless-stopped
    networks:
      - martinnet

  image-processor:
    container_name: image-processor
    build: ./imageprocessor
    volumes:
      - /volume1/docker/imageprocessor/input:/data
      - /volume1/docker/imageprocessor/output:/library
      - /volume1/docker/imageprocessor/archive:/archive
    restart: unless-stopped
    networks:
      - martinnet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYmE3ODc2MjJmMTlhYzNjZTIzNDk5YzRkZTVjYjVjMDMiLCJ0IjoiNzAwZTU4MDUtNzZhNC00NzgwLTgyYTEtMmQ3YzkxZDkwMmRmIiwicyI6Ik56SmlZbUUwWmpNdE1EazNaUzAwWXpneUxUa3paamt0TnpkbU56ZzJNemN3TUdFeE5HVXdaRE5qWldRdE1qRmhOeTAwT0RSbUxUbGxOalV0WTJNd1lqUmtNakpqWTJJMSJ9
    networks:
      - martinnet

  r6assistant-web:
    container_name: r6assistant-web
    build: ./r6assistant

    ports:
      - "8082:8080"

    environment:
      - ASPNETCORE_URLS=http://+:8080

    volumes:
      - /volume1/docker/r6assistant/data:/app/Data

    restart: unless-stopped

    networks:
      - martinnet

networks:
  martinnet:
    driver: bridge