<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMartin.Media.Contracts\ITMartin.Media.Contracts.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Domain\ITMartin.Media.Domain.csproj" />
      <ProjectReference Include="..\ITMartin.OCR\ITMartin.OCR.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pipelines\Package1\Persistence\" />
      <Folder Include="Pipelines\Package2\Enhanced\" />
      <Folder Include="Pipelines\Package2\Manifests\" />
      <Folder Include="Pipelines\Package2\Models\" />
      <Folder Include="Pipelines\Package2\Temp\" />
      <Folder Include="Pipelines\Package2\Thumbnails\" />
      <Folder Include="Pipelines\Package2\Working\" />
      <Folder Include="Services\Steps\FileDiscoveryStep\" />
      <Folder Include="Services\Steps\HashStep\" />
      <Folder Include="Services\Steps\ManifestBuildStep\" />
      <Folder Include="Services\Steps\MetaDataStep\" />
      <Folder Include="Services\Steps\ThumbnailStep\" />
    </ItemGroup>

</Project>
