<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMartin.Media.Contracts\ITMartin.Media.Contracts.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Domain\ITMartin.Media.Domain.csproj" />
      <ProjectReference Include="..\ITMartin.OCR\ITMartin.OCR.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
      <PackageReference Include="MetadataExtractor" Version="2.9.3" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pipelines\Package1\Clients\" />
    </ItemGroup>

</Project>
