<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Jobs\" />
      <Folder Include="Orchestration\" />
      <Folder Include="Recognition\" />
      <Folder Include="Runtime\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMartin.Ai\ITMartin.Ai.csproj" />
      <ProjectReference Include="..\ITMartin.Magic.Domain\ITMartin.Magic.Domain.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Contracts\ITMartin.Media.Contracts.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Domain\ITMartin.Media.Domain.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Infrastructure\ITMartin.Media.Infrastructure.csproj" />
      <ProjectReference Include="..\ITMartin.Media.Runtime\ITMartin.Media.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    </ItemGroup>

</Project>
