<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ITMartinNotatskriver.Server</RootNamespace>
        <AssemblyName>ITMartinNotatskriver.Server</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMartin.Shared.UI\ITMartin.Shared.UI.csproj" />
      <ProjectReference Include="..\ITMartinNotatskriver.Infrastructure\ITMartinNotatskriver.Infrastructure.csproj" />
      <ProjectReference Include="..\ITMartinNotatskriver.Application\ITMartinNotatskriver.Application.csproj" />
      <ProjectReference Include="..\ITMartinNotatskriver.Domain\ITMartinNotatskriver.Domain.csproj" />
    </ItemGroup>

</Project>
