<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ITMartinKigMed.Server</RootNamespace>
        <AssemblyName>ITMartinKigMed.Server</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMartin.Shared.UI\ITMartin.Shared.UI.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="QRCoder" Version="1.8.0" />
    </ItemGroup>

</Project>
