<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ITMartinElPriser.Core</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ITMartinElPriser.Tests" />
  </ItemGroup>

</Project>
