// <auto-generated />
using System;
using ITMartin.Magic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITMartin.Magic.Infrastructure.Migrations
{
    [DbContext(typeof(MagicDbContext))]
    [Migration("20260706084758_AddSetIconUrl")]
    partial class AddSetIconUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITMartin.Magic.Domain.Entities.MagicCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("EurPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("text");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("UsdPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ITMartin.Magic.Domain.Entities.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PriceAlerts");
                });

            modelBuilder.Entity("MagicSetKnowledge", b =>
                {
                    b.Property<string>("SetCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CopyrightStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CopyrightYear")
                        .HasColumnType("integer");

                    b.Property<string>("FrameStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCollectorNumbers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFoils")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSetSymbol")
                        .HasColumnType("boolean");

                    b.Property<string>("IconSvgUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SymbolColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SymbolDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SymbolKeywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SymbolShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UsesBlackBorder")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsesOldFrame")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsesWhiteBorder")
                        .HasColumnType("boolean");

                    b.HasKey("SetCode");

                    b.ToTable("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
