// <auto-generated />
using System;
using ITMartin.Magic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITMartin.Magic.Infrastructure.Migrations
{
    [DbContext(typeof(MagicDbContext))]
    [Migration("20260612165142_AddScanPipeline")]
    partial class AddScanPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagicSetKnowledge", b =>
                {
                    b.Property<string>("SetCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CopyrightStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CopyrightYear")
                        .HasColumnType("integer");

                    b.Property<string>("FrameStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCollectorNumbers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFoils")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSetSymbol")
                        .HasColumnType("boolean");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SymbolColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SymbolDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SymbolKeywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SymbolShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UsesBlackBorder")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsesOldFrame")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsesWhiteBorder")
                        .HasColumnType("boolean");

                    b.HasKey("SetCode");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("ScanImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScanSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScanSessionId");

                    b.ToTable("ScanImages");
                });

            modelBuilder.Entity("ScanResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ScanImageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanImageId");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("ScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ScanSessions");
                });

            modelBuilder.Entity("ScanImage", b =>
                {
                    b.HasOne("ScanSession", "Session")
                        .WithMany("Images")
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScanResult", b =>
                {
                    b.HasOne("ScanImage", null)
                        .WithMany("Results")
                        .HasForeignKey("ScanImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanImage", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ScanSession", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
