// <auto-generated />
using System;
using ITMartin.Magic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITMartin.Magic.Infrastructure.Migrations
{
    [DbContext(typeof(MagicDbContext))]
    partial class MagicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("MagicSetKnowledge", b =>
                {
                    b.Property<string>("SetCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyrightStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CopyrightYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCollectorNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFoils")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSetSymbol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolKeywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesBlackBorder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesOldFrame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesWhiteBorder")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetCode");

                    b.ToTable("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
